[config]
set = false

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.yazi]
input_path = "~/.config/matugen/templates/yazi-theme.toml"
output_path = "~/.config/yazi/theme.toml"

[templates.wlogout]
input_path = "~/.config/matugen/templates/colors.css"
output_path = "~/.config/wlogout/colors.css"

[templates.dunstwl]
input_path = "~/.config/matugen/templates/dunstrc-wayland"
output_path = "~/.config/dunst/dunstrc-wayland"

[templates.dunstx11]
input_path = "~/.config/matugen/templates/dunstrc-x11"
output_path = "~/.config/dunst/dunstrc-x11"

[templates.ags]
input_path = "~/.config/matugen/templates/colors.scss"
output_path = "~/.config/ags/colors.scss"

[templates.discord]
input_path = "~/.config/matugen/templates/discord-colors.css"
output_path = "~/.config/vesktop/settings/quickCss.css"

[templates.i3]
input_path = "~/.config/matugen/templates/i3-config"
output_path = "~/.config/i3/config"
post_hook = "i3-msg reload"
