#!/usr/bin/fish

if count $argv >/dev/null
    if not test -f $argv[1]
        echo "File not found..."
        exit 1
    end

    set -l IMG_PATH $argv[1]
    ln -sf $IMG_PATH ~/.config/hypr/WPP

    if test (string split . $IMG_PATH | tail -n1) = mp4
        rm ~/.config/hypr/asset/LOCK.JPG
        ffmpeg -i $IMG_PATH -vf "select=eq(n\,0)" -q:v 1 ~/.config/hypr/asset/LOCK.JPG
        if not test -f ~/.config/hypr/.vidlock
            swww kill
            touch ~/.config/hypr/.vidlock
        end
        mpvpaper -o "--loop-playlist --hwdec=vaapi" '*' $IMG_PATH >/dev/null &
    else
        if test (string split . $IMG_PATH | tail -n1) = gif
            rm ~/.config/hypr/asset/LOCK.JPG
            ffmpeg -i $IMG_PATH -vframes 1 ~/.config/hypr/asset/LOCK.JPG
        else
            ln -sf ~/.config/hypr/WPP ~/.config/hypr/asset/LOCK.JPG
        end

        if test -f ~/.config/hypr/.vidlock
            kill mpvpaper
            swww-daemon >/dev/null &
            sh -c "rm ~/.config/hypr/.vidlock"
        end
        swww img --transition-type random $IMG_PATH >/dev/null &
    end
else
    set -l IMG_PATH ~/.config/hypr/WPP

    if test -f ~/.config/hypr/.vidlock
        mpvpaper -o "--loop-playlist --hwdec=vaapi" '*' $IMG_PATH >/dev/null &
    else
        swww-daemon >/dev/null &
        swww img --transition-type random $IMG_PATH >/dev/null &
    end
end
