#!/usr/bin/fish

set -l IMG_PATH $argv[1]
set -l IMG_NAME (basename $IMG_PATH)
set -l IMG_CACHE ~/.cache/wpp/$IMG_NAME.JPG
ln -sf $IMG_PATH ~/.config/hypr/WPP

if test (string split . $IMG_PATH | tail -n1) = mp4
    if not test -f $IMG_CACHE
        ffmpeg -i $IMG_PATH -vf "select=eq(n\,0)" -q:v 1 $IMG_CACHE
    end
    if not test -f ~/.config/hypr/.vidlock
        swww kill
        touch ~/.config/hypr/.vidlock
    end
    mpvpaper -o "--loop-playlist --hwdec=vaapi" '*' $IMG_PATH >/dev/null &
else
    if not test -f $IMG_CACHE
        if test (string split . $IMG_PATH | tail -n1) = gif
            ffmpeg -i $IMG_PATH -vframes 1 $IMG_CACHE
        else
            ffmpeg -i $IMG_PATH $IMG_CACHE
        end
    end

    if test -f ~/.config/hypr/.vidlock
        kill mpvpaper
        swww-daemon >/dev/null &
        sh -c "rm ~/.config/hypr/.vidlock"
    end
    swww img --transition-type random $IMG_PATH >/dev/null
end

ln -sf $IMG_CACHE ~/.config/hypr/asset/LOCK.JPG

matugen image $IMG_CACHE
wallust run $IMG_CACHE

cp ~/.cache/wallust/sequences ~/.cache/wal/sequences
sed -i 's/""/"~\/.config\/hypr\/asset\/LOCK.JPG"/g' ~/.cache/wal/colors.json

kitty @ set-colors -a -c ~/.config/kitty/colors.conf
pywalfox update
pkill -USR2 cava
