#!/usr/bin/fish

set -l PID (pidof wl-screenrec)

if [ $PID ]
    kill $PID
    pkill -f "$HOME/.config/hypr/scripts/record_tray.py"
    notify-send "Screen Recording" "Screen Recording stopped"
else
    if [ $argv[1] = select ]
        wl-screenrec --audio -f $HOME/Videos/Records/(date +'%Y%m%d_%Hh%Mm%Ss').mp4 -g (slurp) &
    else
        wl-screenrec --audio -f $HOME/Videos/Records/(date +'%Y%m%d_%Hh%Mm%Ss').mp4 &
    end

    python -u "$HOME/.config/hypr/scripts/record_tray.py" &
    notify-send "Screen Recording" "Screen Recording started"
end
