#!/usr/bin/python

import subprocess
import dateparser

start_data = subprocess.run(["head", "-n1", "/var/log/pacman.log"], capture_output=True)
start_time = dateparser.parse(
    start_data.stdout.decode()[1:25], date_formats=["%Y-%m-%dT%H:%M:%S%z"]
)

current_data = subprocess.run(["date", "-R"], capture_output=True)
current_time = dateparser.parse(
    current_data.stdout.decode(), date_formats=["%a, %d %b %Y %H:%M:%S %z\n"]
)


system_age = current_time - start_time
system_age_hours, system_age_minutes = divmod(
    round(system_age.total_seconds() / 60), 60
)
system_age_hours %= 24
system_age_months, system_age_days = divmod(system_age.days, 61)
if system_age_days > 29:
    system_age_months += 1
    system_age_days -= 30
system_age_years, system_age_months = divmod(system_age_months, 12)

time_labels = ["year", "month", "day", "hour", "minute"]
time_value = [
    system_age_years,
    system_age_months,
    system_age_days,
    system_age_hours,
    system_age_minutes,
]

cnt = 0
for val, label in zip(time_value, time_labels):
    if val:
        cnt += 1
        print(
            f"{val} {label}{'s' if val > 1 else ''}", end=f"{', ' if cnt == 1 else ''}"
        )

        if cnt == 2:
            break
