[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "python"
roots = ["pyproject.toml"]
language-servers = ["pyright", "ruff"]
auto-format = true

[[language]]
name = "jsonc"
comment-token = "//"

[language-server.pyright.config.python.analysis]
typeCheckingMode = "strict"
autoImportCompletions = true

[language-server.rust-analyzer.config]
check.workspace = true
