[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "xml"
auto-format = true
language-servers = ["lemminx"]

[[language]]
name = "qml"
auto-format = true
language-servers = ["qmlls"]

[[language]]
name = "python"
roots = ["pyproject.toml"]
language-servers = ["ty", "ruff"]
auto-format = true

[[language]]
name = "typst"
auto-format = true
formatter = { command = "typstyle" }

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--parser", "markdown"] }
auto-format = true

[[language]]
name = "json"
comment-token = "//"
formatter = { command = "prettier", args = ["--parser", "json"] }
auto-format = true

[[language]]
name = "jsonc"
comment-token = "//"
formatter = { command = "prettier", args = ["--parser", "jsonc"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "scss"
formatter = { command = "prettier", args = ["--parser", "scss"] }
auto-format = true

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "prettier", args = ["--parser", "yaml"] }
auto-format = true

[[language]]
name = "bash"
formatter = { command = "shfmt" }
auto-format = true

[language-server.ty]
command = "ty"
args = ["server"]

[language-server.lemminx]
command = "lemminx"

[language-server.qmlls]
command = "qmlls6"
