[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "python"
roots = ["pyproject.toml"]
language-servers = ["pyright", "ruff"]
auto-format = true

[[language]]
name = "jsonc"
comment-token = "//"
auto-format = true

[[language]]
name = "typst"
auto-format = true
formatter = { command = "typstyle" }

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

[language-server.pyright.config.python.analysis]
typeCheckingMode = "strict"
autoImportCompletions = true
