[display]
code_editor_font_size = 13
cell_output = "above"
dataframes = "rich"
default_width = "medium"
default_table_page_size = 11
theme = "dark"

[diagnostics]
enabled = true

[ai]
rules = ""

[ai.bedrock]

[ai.google]

[ai.anthropic]

[ai.open_ai]

[snippets]
custom_paths = []
include_default_snippets = true

[keymap]
preset = "default"

[keymap.overrides]

[server]
browser = "default"
follow_symlink = true

[save]
autosave_delay = 1000
autosave = "after_delay"
format_on_save = true

[completion]
activate_on_typing = true
copilot = "github"

[language_servers.pylsp]
enable_mypy = true
enable_pyflakes = false
enable_pylint = false
enable_pydocstyle = true
enabled = true
enable_ruff = true
enable_flake8 = false

[package_management]
manager = "uv"

[formatting]
line_length = 80

[runtime]
reactive_tests = true
std_stream_max_bytes = 1000000
auto_instantiate = true
on_cell_change = "autorun"
auto_reload = "autorun"
watcher_on_save = "autorun"
output_max_bytes = 8000000
default_sql_output = "auto"

[experimental]
