[formatting]
line_length = 80

[runtime]
on_cell_change = "autorun"
auto_reload = "autorun"
reactive_tests = true
watcher_on_save = "autorun"
output_max_bytes = 8000000
auto_instantiate = true
std_stream_max_bytes = 1000000
default_sql_output = "auto"

[language_servers.pylsp]
enable_ruff = true
enable_mypy = true
enable_pyflakes = false
enable_pylint = false
enable_flake8 = false
enabled = true
enable_pydocstyle = true

[display]
cell_output = "above"
default_table_page_size = 11
code_editor_font_size = 13
dataframes = "rich"
theme = "dark"
default_width = "medium"

[experimental]

[completion]
copilot = "github"
activate_on_typing = true

[server]
follow_symlink = true
browser = "default"

[save]
format_on_save = true
autosave = "after_delay"
autosave_delay = 1000

[keymap]
preset = "default"

[keymap.overrides]

[ai]
rules = ""

[ai.anthropic]

[ai.open_ai]

[ai.google]

[ai.bedrock]

[diagnostics]
enabled = true

[package_management]
manager = "uv"

[snippets]
custom_paths = []
include_default_snippets = true
