backend = "wal"
color_space = "lchmixed"
check_contrast = true

[templates]
kitty = { src = 'kitty.conf', dst = '~/.config/kitty/colors.conf' }
hyprland = { src = 'hyprland.conf', dst = '~/.config/hypr/border.conf' }
hyprlock = { src = 'hyprlock.conf', dst = '~/.config/hypr/colors.conf' }
firefox = { src = 'pywalfox.json', dst = '~/.cache/wal/colors.json' }
