backend = "wal"
color_space = "lchmixed"
check_contrast = true

[templates]
kitty = { src = 'kitty.conf', dst = '~/.config/kitty/colors.conf' }
hypr = { src = 'hyprland.conf', dst = '~/.config/hypr/border.conf' }
