[config]
set = false

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.yazi]
input_path = "~/.config/matugen/templates/yazi-theme.toml"
output_path = "~/.config/yazi/theme.toml"

[templates.wlogout]
input_path = "~/.config/matugen/templates/colors.css"
output_path = "~/.config/wlogout/colors.css"

[templates.ags]
input_path = "~/.config/matugen/templates/colors.scss"
output_path = "~/.config/ags/colors.scss"

[templates.pywalfox]
input_path = "~/.config/matugen/templates/pywalfox-colors.json"
output_path = "~/.cache/wal/colors.json"
post_hook = "pywalfox update"

[templates.discord]
input_path = "~/.config/matugen/templates/discord-colors.css"
output_path = "~/.config/vesktop/settings/quickCss.css"

[templates.zathura]
input_path = "~/.config/matugen/templates/zathura-colors"
output_path = "~/.config/zathura/colors"
