[general]
import = ["colors.toml"]

[window]
opacity = 0.9

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
size = 7.25

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 500
blink_timeout = 0
unfocused_hollow = true
